"""add colomn njk_memo

Revision ID: 678e293cb579
Revises: 6c9929ee202b
Create Date: 2025-04-09 11:05:36.770664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678e293cb579'
down_revision = '6c9929ee202b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('njk_memo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_njk_memo_present', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_detail_accessed', sa.Boolean(), nullable=False))

    with op.batch_alter_table('job_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('njk_memo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_njk_memo_present', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_detail_accessed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_emails', schema=None) as batch_op:
        batch_op.drop_column('is_detail_accessed')
        batch_op.drop_column('is_njk_memo_present')
        batch_op.drop_column('njk_memo')

    with op.batch_alter_table('contact_emails', schema=None) as batch_op:
        batch_op.drop_column('is_detail_accessed')
        batch_op.drop_column('is_njk_memo_present')
        batch_op.drop_column('njk_memo')

    # ### end Alembic commands ###
