"""問い合わせメールと求人関係メールのテーブル作成

Revision ID: 6c9929ee202b
Revises: 
Create Date: 2025-01-29 10:39:56.286531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9929ee202b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_type', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(length=3000), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kana', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=200), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_emails_received_at'), ['received_at'], unique=False)

    op.create_table('job_emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_emails_received_at'), ['received_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_emails_received_at'))

    op.drop_table('job_emails')
    with op.batch_alter_table('contact_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_emails_received_at'))

    op.drop_table('contact_emails')
    # ### end Alembic commands ###
